language: python
python: 2.7

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_validate
    - OMV_ENGINE=PyLEMS_NeuroML2

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all
    - pwd
    - ls -alt
    - ls -alt NeuroML2
    
    
    

