language: python
python: 2.7

env:
    - OMV_ENGINE=jNeuroML

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation@test_new_backends

script:
    - omv all
    
    
    

