language: python
python: 2.7

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation@test_new_backends

script:
    - omv all
    - pwd
    - ls -alt
    - ls -alt NeuroML2
    
    
    

